name: generate pacman game

on:
  schedule:
    - cron: "0 0 * * *" # Every 24 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move generated file
        run: |
          mkdir -p output
          mv dist/*.svg output/

      - name: Verify SVG output
        run: ls -R output

      - name: Commit and push generated SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update pacman contribution graph"
          add: "output/*.svg"
